# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Projects"
  url = "#project"
  weight = 2

[[main]]
  name = "Publications"
  url = "publication/"
  weight = 3

[[main]]
  name = "Talks"
  url = "talk/"
  weight = 4

[[main]]
  name = "Blog"
  url = "post/"
  weight = 5

[[main]]
  name = "CV"
  url = "files/cv.pdf"
  weight = 6

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 7

